# Generated by Django 4.1 on 2022-08-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="movie",
            new_name="movie_id",
        ),
    ]
